INSERT INTO music_recommendation (title, artist, album, youtube_url, spotify_url, art_url, notes, tags)
VALUES
    ('Vampire Empire', 'Big Thief', 'Vampire Empire',
     'https://www.youtube.com/watch?v=Ka1vNzmD6JE',
     'https://open.spotify.com/track/4SwSpxsOYtnEaRxWtYrnvZ?si=0cb8398e39254f18',
     '/music_art/bigthief_vampire.jpg',
     NULL,
     ARRAY['indie folk','americana']),

    ('Natural Blues', 'Moby', 'Play',
     'https://www.youtube.com/watch?v=SC6-TiN19uE',
     'https://open.spotify.com/track/19aUcBFBrXbsAcucaVFBjW?si=97d7fc2aac164542',
     '/music_art/moby_play.JPG',
     NULL,
     ARRAY['electronica','ambient']),

    ('Reckoner', 'Radiohead', 'In Rainbows',
     'https://www.youtube.com/watch?v=i9rN9eY2hRc',
     'https://open.spotify.com/track/02ppMPbg1OtEdHgoPqoqju?si=6692ddd89e734fe0',
     '/music_art/radiohead_rainbows.png',
     NULL,
     ARRAY['art rock','electronica']),

     ('Mystery of Love (Demo)', 'Sufjan Stevens', 'Carrie & Lowell',
     'https://www.youtube.com/watch?v=gNDuNpxpRkY',
     'https://open.spotify.com/track/62RTXxio7jbtBTxWz43JPS?si=a4ead919f3ac408d',
     '/music_art/sufjan_carrie.jpeg',
     NULL,
     ARRAY['indie folk','lo-fi']),

     ('Almost Cut My Hair', 'Crosby, Stills, Nash & Young', 'Deja Vu',
     'https://www.youtube.com/watch?v=4Lk2KHajp4Y',
     'https://open.spotify.com/track/0gCJkpD0RhF2rjiALLHBQL?si=2366fa0e16844c53',
     '/music_art/CSNY_DejaVu.jpg',
     NULL,
     ARRAY['folk rock','country rock']),

     ('Soul to Squeeze', 'Red Hot Chili Peppers', 'Soul to Squeeze',
     'https://www.youtube.com/watch?v=0XcN12uVHeQ',
     'https://open.spotify.com/track/3arKRnq9OUd7yq6LRwVW8I?si=f6a4e2cef460462f',
     '/music_art/rhcp_soul.jpg',
     NULL,
     ARRAY['funk rock','alternative rock']),

     ('Drive', 'Incubus', 'Soul to Squeeze',
     'https://www.youtube.com/watch?v=fgT9zGkiLig',
     'https://open.spotify.com/track/7nnWIPM5hwE3DaUBkvOIpy?si=91f369b8431c42d8',
     '/music_art/incubus_make.jpeg',
     NULL,
     ARRAY['grunge','alternative rock']),

     ('The Magician', 'Andy Shauf', 'The Party',
     'https://www.youtube.com/watch?v=PN0RPWII7gY',
     'https://open.spotify.com/track/3dsd09qrt34YuS6NPbQtYq?si=7811c7745d6746ed',
     '/music_art/andy_party.jpg',
     NULL,
     ARRAY['folk rock','indie pop']),

     ('A Pair of Brown Eyes', 'The Pogues', 'Rum Sodomy & The Lash',
     'https://www.youtube.com/watch?v=zNtQ5AnRlz8',
     'https://open.spotify.com/track/32soEc9h0wDy1BEjV5egeh?si=dc874d3ea6f04302',
     '/music_art/pogues_rum.jpg',
     NULL,
     ARRAY['celtic punk','folk punk']),

     ('505', 'Arctic Monkey', 'Favourite Worst Nightmare',
     'https://www.youtube.com/watch?v=MrmPDUvKyLs',
     'https://open.spotify.com/track/58ge6dfP91o9oXMzq3XkIS?si=0301a8f5a8124c2a',
     '/music_art/arctic_worst.jpg',
     NULL,
     ARRAY['indie rock','post-punk revival']),

     ('Lightning Crashes', 'Live', 'Throwing Copper',
     'https://www.youtube.com/watch?v=xsJ4O-nSveg',
     'https://open.spotify.com/track/48iWbsOaBUAGzMdoSmqyg1?si=8668bc76d5b84733',
     '/music_art/live_copper.jpg',
     NULL,
     ARRAY['grunge','alternative rock']),

     ('Golden Brown', 'The Stranglers', 'La Folie',
     'https://www.youtube.com/watch?v=AWAsI3U2EaE',
     'https://open.spotify.com/track/2AX5E86cn9n2dgioZEjirI?si=b84afd7508e04b16',
     '/music_art/stranglers_la.jpeg',
     NULL,
     ARRAY['new wave','art rock']),

     ('Sinnerman', 'Nina Simone', 'Pastel Blues',
     'https://www.youtube.com/watch?v=QH3Fx41Jpl4',
     'https://open.spotify.com/track/5xRP5iyVdGglqlY4Vcjhkx?si=7ae195e3acea4e32',
     '/music_art/nina_blues.jpg',
     NULL,
     ARRAY['blues','jazz']),

     ('Baltimore', 'Nina Simone', 'Baltimore',
     'https://www.youtube.com/watch?v=ztCgNQg9FCQ',
     'https://open.spotify.com/track/39CyGKIFqMzSuynOR8uilD?si=2f68c93e2eb34bd8',
     '/music_art/nina_baltimore.jpg',
     NULL,
     ARRAY['blues','jazz']),

     ('Figaro', 'MF DOOM', 'Madvillainy',
     'https://www.youtube.com/watch?v=A7_0vcjN-4c',
     'https://open.spotify.com/track/7oFiFPltiQTBqVutyiSwvE?si=022ae26863fa41ac',
     '/music_art/mfdoom_mad.png',
     NULL,
     ARRAY['jazz rap','psychedelic rap']),

     ('Nights', 'Frank Ocean', 'Blonde',
     'https://www.youtube.com/watch?v=r4l9bFqgMaQ',
     'https://open.spotify.com/track/7eqoqGkKwgOaWNNHx90uEZ?si=582bb017b8674cd8',
     '/music_art/frank_blonde.jpeg',
     NULL,
     ARRAY['R&B','avant-soul']),

     ('Self Control', 'Frank Ocean', 'Blonde',
     'https://www.youtube.com/watch?v=BME88lS6aVY',
     'https://open.spotify.com/track/5GUYJTQap5F3RDQiCOJhrS?si=0e2ba2d9f67c45c8',
     '/music_art/frank_blonde.jpeg',
     NULL,
     ARRAY['R&B','avant-soul']),

    ('Gypsy', 'Fleetwood Mac', 'Gypsy',
     'https://www.youtube.com/watch?v=mwgg1Pu6cNg',
     'https://open.spotify.com/track/19Ym5Sg0YyOCa6ao21bdoG?si=a0288113401c4035',
     '/music_art/fleetwood_gypsy.jpg',
     NULL,
     ARRAY['blues rock','soft rock']),

     ('Rhiannon - Live', 'Fleetwood Mac', 'The Dance',
     'https://www.youtube.com/watch?v=jzOsQAMtpm0',
     'https://open.spotify.com/track/6ogxNURdCpRGmtOYbECyqg?si=4013fe610c7a4b15',
     '/music_art/fleetwood_dance.jpg',
     NULL,
     ARRAY['blues rock','soft rock']),

     ('Big Love - Live', 'Fleetwood Mac', 'The Dance',
     'https://www.youtube.com/watch?v=mZZp76M4NGc',
     'https://open.spotify.com/track/4XYQtNf5BxGeAiwR0YU2Gn?si=0d2d95702e37447d',
     '/music_art/fleetwood_dance.jpg',
     NULL,
     ARRAY['blues rock','soft rock']),

     ('Tea for Two', 'Albert Hammond Jr', 'Francis Trouble',
     'https://www.youtube.com/watch?v=KH6SJYV2y38',
     'https://open.spotify.com/track/68qYhu1du0kbiyAtnIKNLh?si=6e70c649efad4931',
     '/music_art/albert_francis.jpg',
     NULL,
     ARRAY['garage rock','post-punk revival']),

     ('Only For You', 'Heartless Bastards', 'Arrow',
     'https://www.youtube.com/watch?v=2l4alp0De8Y',
     'https://open.spotify.com/track/4KwvTXx3yR0FA4LGfxD4xP?si=f818af23e5624653',
     '/music_art/heartless_arrow.jpeg',
     NULL,
     ARRAY['blues rock','folk rock']),

     ('Sometimes', 'Goth Babe', 'Sometimes',
     'https://www.youtube.com/watch?v=kQrRNOmTRSA',
     'https://open.spotify.com/track/7oJmIBxEAYjfkS7lhZ7M1S?si=e6c23378936e4fdd',
     '/music_art/goth_sometimes.jpeg',
     NULL,
     ARRAY['trance pop','indie rock']),

     ('Live Well', 'Palace', 'So Long Forever',
     'https://www.youtube.com/watch?v=f6noiVByjzM',
     'https://open.spotify.com/track/2H30WL3exSctlDC9GyRbD4?si=66370e000d314561',
     '/music_art/palace_solong.jpeg',
     NULL,
     ARRAY['trance rock','alternative rock']),

     ('Live Well', 'Palace', 'So Long Forever',
     'https://www.youtube.com/watch?v=2_n1L-ikqZk',
     'https://open.spotify.com/track/2DkZisoN9h1dLa8Sn5sx0n?si=70e95a2390084ee8',
     '/music_art/palace_solong.jpeg',
     NULL,
     ARRAY['trance rock','alternative rock']),

     ('Imagining My Man', 'Aldous Harding', 'Party',
     'https://www.youtube.com/watch?v=xE-A0cNSLmc',
     'https://open.spotify.com/track/0B4U4UMwO5uKqM3OXm6L6P?si=7b444cb287fc44bd',
     '/music_art/aldous_party.png',
     NULL,
     ARRAY['folk','alternative']),

     ('Pressure To Party', 'Julia Jacklin', 'Crushing',
     'https://www.youtube.com/watch?v=CZFyqzTCt-I',
     'https://open.spotify.com/track/480rD34KfGbMaT0L6zjeIu?si=7836dfc0787e4ef6',
     '/music_art/julia_crushing.png',
     NULL,
     ARRAY['indie rock','alternative']),

     ('Blood And Tears', 'Danzig', 'Danzig II - Lucifuge',
     'https://www.youtube.com/watch?v=EG0lNvJ9q84',
     'https://open.spotify.com/track/1Gt07aYIpl5yJcTbH95s7v?si=47cc8e6cf6214663',
     '/music_art/danzig_II.jpg',
     NULL,
     ARRAY['blues rock','heavy metal']),

     ('wonder eye', 'Little Moon', 'wonder eye',
     'https://www.youtube.com/watch?v=yncJDUkOY0c',
     'https://open.spotify.com/track/33LGjweq5DMLg7GeZkXuUj?si=e73a7f646d174b28',
     '/music_art/wonder_eye.jpeg',
     NULL,
     ARRAY['indie folk','alternative folk']),

     ('Kiss City', 'Blondshell', 'Blondshell',
     'https://www.youtube.com/watch?v=KeL-islGZuQ',
     'https://open.spotify.com/track/1YlqPQXvRAUzDYAkqNw89K?si=7df67610d39c4d0e',
     '/music_art/blondshell.jpg',
     NULL,
     ARRAY['indie rock','grunge'])

ON CONFLICT ON CONSTRAINT uq_music_title_artist DO NOTHING;