CREATE TABLE IF NOT EXISTS movie_recommendation (
    id              BIGSERIAL PRIMARY KEY,
    title           TEXT,
    director        TEXT,
    release_year    INT,
    imdb_url        TEXT,
    letterboxd_url  TEXT,
    art_url         TEXT,
    tagline         TEXT,
    blurb           TEXT,
    genres          TEXT[],
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Prevent duplicate seeds by (title, release_year)
ALTER TABLE movie_recommendation
    ADD CONSTRAINT uq_movie_title_year UNIQUE (title, release_year);

INSERT INTO movie_recommendation (
    title,
    director,
    release_year,
    imdb_url,
    letterboxd_url,
    art_url,
    tagline,
    blurb,
    genres
)
VALUES
    ('Cool Hand Luke', 'Stuart Rosenberg', 1967,
     'https://www.imdb.com/title/tt0061512/',
     'https://letterboxd.com/film/cool-hand-luke/',
     '/movie_art/coolHandLuke.jpg',
     'Sometimes nothin’ can be a real cool hand.',
     'When petty criminal Luke Jackson is sentenced to two years in a Florida prison farm, he doesn’t play by the rules of either the sadistic warden or the yard’s resident heavy, Dragline, who ends up admiring the new guy’s unbreakable will. Luke’s bravado, even in the face of repeated stints in the prison’s dreaded solitary confinement cell, “the box,” make him a rebel hero to his fellow convicts and a thorn in the side of the prison officers.',
     ARRAY['drama','crime','tragedy']),

    ('Network', 'Sidney Lumet', 1976,
     'https://www.imdb.com/title/tt0074958/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_network',
     'https://letterboxd.com/film/network/',
     '/movie_art/network.jpg',
     'Television will never be the same.',
     'When veteran anchorman Howard Beale is forced to retire his 25-year post because of his age, he announces to viewers that he will kill himself during his farewell broadcast. Network executives rethink their decision when his fanatical tirade results in a spike in ratings.',
     ARRAY['drama','dark comedy']),

     ('The Big Lebowski', 'Coen Brothers', 1998,
     'https://www.imdb.com/title/tt0118715/?ref_=nv_sr_srsg_3_tt_6_nm_2_in_0_q_the%2520big%2520',
     'https://letterboxd.com/film/the-big-lebowski/',
     '/movie_art/lebowski.jpeg',
     'The Dude abides.',
     'Jeffrey ‘The Dude’ Lebowski, a Los Angeles slacker who only wants to bowl and drink White Russians, is mistaken for another Jeffrey Lebowski, a wheelchair-bound millionaire, and finds himself dragged into a strange series of events involving nihilists, adult film producers, ferrets, errant toes, and large sums of money.',
     ARRAY['comedy','dark comedy','crime','satire']),

     ('There Will Be Blood', 'Paul Thomas Anderson', 2007,
     'https://www.imdb.com/title/tt0469494/?ref_=fn_t_1',
     'https://letterboxd.com/film/there-will-be-blood/',
     '/movie_art/blood.jpg',
     'There will be greed. There will be vengeance.',
     'Ruthless silver miner, turned oil prospector, Daniel Plainview, moves to oil-rich California. Using his son to project a trustworthy, family-man image, Plainview cons local landowners into selling him their valuable properties for a pittance. However, local preacher Eli Sunday suspects Plainview’s motives and intentions, starting a slow-burning feud that threatens both their lives.',
     ARRAY['drama','epic','period drama','tragedy']),

     ('True Grit', 'Coen Brothers', 2010,
     'https://www.imdb.com/title/tt1403865/?ref_=fn_t_1',
     'https://letterboxd.com/film/true-grit-2010/',
     '/movie_art/trueGrit.jpg',
     'Punishment comes one way or another.',
     'Following the murder of her father by a hired hand, a 14-year-old farm girl sets out to capture the killer. To aid her, she hires the toughest U.S. Marshal she can find—a man with ‘true grit’—Reuben J. ‘Rooster’ Cogburn.',
     ARRAY['western','drama','period drama']),

     ('No Country for Old Men', 'Coen Brothers', 2007,
     'https://www.imdb.com/title/tt0477348/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_no%2520country%2520for%2520old%2520m',
     'https://letterboxd.com/film/no-country-for-old-men/',
     '/movie_art/noCountry.jpg',
     'There are no clean getaways.',
     'Llewelyn Moss stumbles upon dead bodies, $2 million and a hoard of heroin in a Texas desert, but methodical killer Anton Chigurh comes looking for it, with local sheriff Ed Tom Bell hot on his trail. The roles of prey and predator blur as the violent pursuit of money and justice collide.',
     ARRAY['western','crime','drama','thriller']),

     ('One Battle After Another', 'Paul Thomas Anderson', 2025,
     'https://www.imdb.com/title/tt30144839/?ref_=nv_sr_srsg_0_tt_3_nm_0_in_0_q_one%2520battle%2520after%2520',
     'https://letterboxd.com/film/one-battle-after-another/',
     '/movie_art/oneBattle.jpg',
     'Some search for battle, others are born into it.',
     'When their evil nemesis resurfaces after 16 years, a band of ex-revolutionaries reunite to rescue the daughter of one of their own.',
     ARRAY['thriller','dark comedy','epic','action']),

     ('The Thing', 'John Carpenter', 1982,
     'https://www.imdb.com/title/tt0084787/?ref_=fn_t_1',
     'https://letterboxd.com/film/the-thing/',
     '/movie_art/thing.jpg',
     'Anytime. Anywhere. Anyone.',
     'A twelve-man team at a remote Antarctic research station discovers an alien buried in the snow for over 100,000 years. Soon unfrozen, the form-changing creature wreaks havoc, creates terror… And becomes one of them.',
     ARRAY['mystery','sci-fi','horror']),

     ('Weapons', 'Zach Cregger', 2025,
     'https://www.imdb.com/title/tt26581740/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_weapons',
     'https://letterboxd.com/film/weapons-2025/',
     '/movie_art/weapons.jpg',
     'Last night at 2:17 AM, every child from Mrs. Gandy’s class woke up, got out of bed, went downstairs, opened the front door, walked into the dark …and they never came back.',
     'When all but one child from the same class mysteriously vanish on the same night at exactly the same time, a community is left questioning who or what is behind their disappearance.',
     ARRAY['horror','mystery','dark comedy']),

     ('1917', 'Sam Mendes', 2019,
     'https://www.imdb.com/title/tt8579674/?ref_=fn_t_1',
     'https://letterboxd.com/film/1917/',
     '/movie_art/1917.jpg',
     'Time is the enemy.',
     'At the height of the First World War, two young British soldiers must cross enemy territory and deliver a message that will stop a deadly attack on hundreds of soldiers.',
     ARRAY['action','war','drama','period drama']),

     ('The Prestige', 'Christopher Nolan', 2006,
     'https://www.imdb.com/title/tt0482571/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_the%2520prestige',
     'https://letterboxd.com/film/the-prestige/',
     '/movie_art/prestige.jpg',
     'Are You Watching Closely?',
     'A mysterious story of two magicians whose intense rivalry leads them on a life-long battle for supremacy – full of obsession, deceit and jealousy with dangerous and deadly consequences.',
     ARRAY['period drama','drama','mystery','sci-fi']),

     ('La Haine', 'Mathieu Kassovitz', 1995,
     'https://www.imdb.com/title/tt0113247/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_la%2520haine',
     'https://letterboxd.com/film/la-haine/',
     '/movie_art/haine.jpg',
     'How far you fall doesn’t matter, it’s how you land…',
     'After a chaotic night of rioting in a marginal suburb of Paris, three young friends, Vinz, Hubert and Saïd, wander around unoccupied waiting for news about the state of health of a mutual friend who has been seriously injured when confronting the police.',
     ARRAY['drama','crime','french','black and white']),

     ('Parasite', 'Bong Joon Ho', 2019,
     'https://www.imdb.com/title/tt6751668/?ref_=fn_t_1',
     'https://letterboxd.com/film/parasite-2019/',
     '/movie_art/parasite.jpg',
     'Act like you own the place.',
     'All unemployed, Ki-taek’s family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.',
     ARRAY['drama','dark comedy','korean','thriller']),

     ('Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb', 'Stanley Kubrick', 1964,
     'https://www.imdb.com/title/tt0057012/?ref_=nv_sr_srsg_6_tt_8_nm_0_in_0_q_dr%2520stra',
     'https://letterboxd.com/film/dr-strangelove-or-how-i-learned-to-stop-worrying-and-love-the-bomb/',
     '/movie_art/strangelove.jpg',
     'Gentlemen, you can’t fight in here. This is the War Room!',
     'After the insane General Jack D. Ripper initiates a nuclear strike on the Soviet Union, a war room full of politicians, generals and a Russian diplomat all frantically try to stop the nuclear strike.',
     ARRAY['comedy','dark comedy','war','political drama']),

     ('Eternal Sunshine of the Spotless Mind', 'Michel Gondry', 2004,
     'https://www.imdb.com/title/tt0338013/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_eterna',
     'https://letterboxd.com/film/eternal-sunshine-of-the-spotless-mind/',
     '/movie_art/eternal.jpg',
     'You can erase someone from your mind. Getting them out of your heart is another story.',
     'Joel Barish, heartbroken that his girlfriend underwent a procedure to erase him from her memory, decides to do the same. However, as he watches his memories of her fade away, he realises that he still loves her, and may be too late to correct his mistake.',
     ARRAY['romance','drama','sci-fi','dark comedy']),

     ('Casablanca', 'Michael Curtiz', 1942,
     'https://www.imdb.com/title/tt0034583/?ref_=nv_sr_srsg_0_tt_7_nm_1_in_0_q_casabla',
     'https://letterboxd.com/film/casablanca/',
     '/movie_art/casablanca.jpg',
     'They had a date with fate in Casablanca!',
     'In Casablanca, Morocco in December 1941, a cynical American expatriate meets a former lover, with unforeseen complications.',
     ARRAY['romance','drama','war','black and white']),

     ('Memories of Murder', 'Boon Joon Ho', 2003,
     'https://www.imdb.com/title/tt0353969/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_memories%2520',
     'https://letterboxd.com/film/memories-of-murder/',
     '/movie_art/memories.jpg',
     'The worst of them will stay with you… forever.',
     'During the late 1980s, two detectives in a South Korean province attempt to solve series of gruesome rape-and-murder of young women.',
     ARRAY['thriller','crime','drama','korean']),

     ('Dog Day Afternoon', 'Sidney Lumet', 1975,
     'https://www.imdb.com/title/tt0072890/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_dog%2520day%2520a',
     'https://letterboxd.com/film/dog-day-afternoon/',
     '/movie_art/dogday.jpg',
     'Anything can happen during the dog days of summer. On August 22nd, 1972, everything did.',
     'Based on the true story of would-be Brooklyn bank robbers John Wojtowicz and Salvatore Naturile. Sonny and Sal attempt a bank heist which quickly turns sour and escalates into a hostage situation and stand-off with the police. As Sonny’s motives for the robbery are slowly revealed and things become more complicated, the heist turns into a media circus.',
     ARRAY['thriller','crime','drama']),

     ('Who’s Afraid of Virginia Woolf?', 'Mike Nichols', 1966,
     'https://www.imdb.com/title/tt0061184/?ref_=nv_sr_srsg_0_tt_7_nm_1_in_0_q_virginia%2520woolf',
     'https://letterboxd.com/film/whos-afraid-of-virginia-woolf/',
     '/movie_art/woolf.jpg',
     'You are cordially invited to George and Martha’s for an evening of fun and games.',
     'A history professor and his wife entertain a young couple who are new to the university’s faculty. As the drinks flow, secrets come to light, and the middle-aged couple unload onto their guests the full force of the bitterness, dysfunction, and animosity that defines their marriage.',
     ARRAY['drama','dark comedy']),

     ('Contact', 'Robert Zemeckis', 1997,
     'https://www.imdb.com/title/tt0118884/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_contact',
     'https://letterboxd.com/film/contact/',
     '/movie_art/contact.jpg',
     'Take a journey to the heart of the universe.',
     'A radio astronomer receives the first extraterrestrial radio signal ever picked up on Earth. As the world powers scramble to decipher the message and decide upon a course of action, she must make some difficult decisions between her beliefs, the truth, and reality.',
     ARRAY['sci-fi','mystery','drama','thriller']),

     ('The Abyss', 'James Cameron', 1989,
     'https://www.imdb.com/title/tt0096754/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_the%2520aby',
     'https://letterboxd.com/film/the-abyss/',
     '/movie_art/abyss.jpg',
     'When you get there, you will understand.',
     'A civilian oil rig crew is recruited to conduct a search and rescue effort when a nuclear submarine mysteriously sinks. One diver soon finds himself on a spectacular odyssey 25,000 feet below the ocean’s surface where he confronts a mysterious force that has the power to change the world or destroy it.',
     ARRAY['thriller','adventure','sci-fi','drama']),

     ('Waking Life', 'Richard Linklater', 2001,
     'https://www.imdb.com/title/tt0243017/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_waking%2520life',
     'https://letterboxd.com/film/waking-life/',
     '/movie_art/wakinglife.jpg',
     'Dreams. What are they? An escape from reality or reality itself?',
     'Waking Life is about a young man in a persistent lucid dream-like state. The film follows its protagonist as he initially observes and later participates in philosophical discussions that weave together issues like reality, free will, our relationships with others, and the meaning of life.',
     ARRAY['animation','drama','surreal','fantasy']),

     ('Adaptation.', 'Spike Jonze', 2002,
     'https://www.imdb.com/title/tt0268126/?ref_=fn_t_1',
     'https://letterboxd.com/film/adaptation/',
     '/movie_art/adapt.jpg',
     'What I came to understand is that change is not a choice. Not for a species of plant, and not for me. It happens - and you are different.',
     'Charlie Kaufman is a confused L.A. screenwriter overwhelmed by feelings of inadequacy, sexual frustration, self-loathing, and by the screenwriting ambitions of his freeloading twin brother Donald. While struggling to adapt “The Orchid Thief,” by Susan Orlean, Kaufman’s life spins from pathetic to bizarre. The lives of Kaufman, Orlean’s book, become strangely intertwined as each one’s search for passion collides with the others’.',
     ARRAY['drama','dark comedy','crime']),

     ('Friday Night Lights', 'Peter Berg', 2004,
     'https://www.imdb.com/title/tt0390022/?ref_=nv_sr_srsg_3_tt_8_nm_0_in_0_q_friday%2520night%2520',
     'https://letterboxd.com/film/friday-night-lights/',
     '/movie_art/fridaylights.jpg',
     'Hope comes alive on Friday nights.',
     'A small, turbulent town in Texas obsesses over their high school football team to an unhealthy degree. When the star tailback, Boobie Miles, is seriously injured during the first game of the season, all hope is lost, and the town’s dormant social problems begin to flare up. It is left to the inspiring abilities of new coach Gary Gaines to instill in the other team members – and, by proxy, the town itself – a sense of self-respect and honor.',
     ARRAY['drama','sports','action']),

     ('The Graduate', 'Mike Nichols', 1967,
     'https://www.imdb.com/title/tt0061722/?ref_=fn_t_1',
     'https://letterboxd.com/film/the-graduate/',
     '/movie_art/graduate.jpg',
     'This is Benjamin. He’s a little worried about his future.',
     '',
     ARRAY['drama','comedy','romance']),

     ('O Brother, Where Art Thouh?', 'Coen Brothers', 2000,
     'https://www.imdb.com/title/tt0190590/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_o%2520broth',
     'https://letterboxd.com/film/o-brother-where-art-thou/',
     '/movie_art/obrother.jpg',
     'They have a plan, but not a clue.',
     'In the deep south during the 1930s, three escaped convicts search for hidden treasure while a relentless lawman pursues them.',
     ARRAY['comedy','adventure','crime','period drama','dark comedy']),

     ('The Truman Show', 'Peter Weir', 1998,
     'https://www.imdb.com/title/tt0120382/?ref_=nv_sr_srsg_0_tt_4_nm_4_in_0_q_truman',
     'https://letterboxd.com/film/the-truman-show/genres/',
     '/movie_art/truman.jpg',
     'On the air. Unaware.',
     'An insurance salesman begins to suspect that his whole life is actually some sort of reality TV show.',
     ARRAY['comedy','drama','dark comedy']),

     ('Almost Famous', 'Cameron Crowe', 2000,
     'https://www.imdb.com/title/tt0181875/?ref_=fn_t_1',
     'https://letterboxd.com/film/almost-famous/',
     '/movie_art/famous.jpg',
     'Experience it. Enjoy it. Just don’t fall for it.',
     'In 1973, 15-year-old William Miller’s unabashed love of music and aspiration to become a rock journalist lands him an assignment from Rolling Stone magazine to interview and tour with the up-and-coming band, Stillwater.',
     ARRAY['drama','music','period drama','dark comedy']),

     ('A League of Their Own', 'Penny Marshall', 1992,
     'https://www.imdb.com/title/tt0104694/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_A%2520league',
     'https://letterboxd.com/film/a-league-of-their-own/',
     '/movie_art/league.jpg',
     'Once in a lifetime you get a chance to do something different.',
     'As America’s stock of athletic young men is depleted during World War II, a professional all-female baseball league springs up in the Midwest, funded by publicity-hungry candy maker Walter Harvey. Competitive sisters Dottie Hinson and Kit Keller spar with each other, scout Ernie Capadino and grumpy has-been coach Jimmy Dugan on their way to fame.',
     ARRAY['comedy','sports','period drama']),

     ('The Killing Fields', 'Roland Joffé', 1984,
     'https://www.imdb.com/title/tt0087553/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_the%2520killing%2520f',
     'https://letterboxd.com/film/the-killing-fields/',
     '/movie_art/killing.jpg',
     'Here, only the silent survive.',
     'New York Times reporter Sydney Schanberg is on assignment covering the Cambodian Civil War, with the help of local interpreter Dith Pran and American photojournalist Al Rockoff. When the U.S. Army pulls out amid escalating violence, Schanberg makes exit arrangements for Pran and his family. Pran, however, tells Schanberg he intends to stay in Cambodia to help cover the unfolding story — a decision he may regret as the Khmer Rouge rebels move in.',
     ARRAY['war','drama','period drama','history']),

     ('The Right Stuff', 'Philip Kaufman', 1983,
     'https://www.imdb.com/title/tt0086197/?ref_=fn_t_1',
     'https://letterboxd.com/film/the-right-stuff/',
     '/movie_art/rightstuff.jpg',
     'How the future began.',
     'At the dawn of the Space Race, seven test pilots set out to become the first American astronauts to enter space. However, the road to making history brings momentous challenges.',
     ARRAY['drama','epic','period drama','history','adventure']),

     ('Jerry Maguire', 'Cameron Crowe', 1996,
     'https://www.imdb.com/title/tt0116695/?ref_=nv_sr_srsg_0_tt_3_nm_5_in_0_q_jerry%2520ma',
     'https://letterboxd.com/film/jerry-maguire/',
     '/movie_art/jerry.jpg',
     'Everybody loved him… Everybody disappeared. The journey is everything.',
     'Jerry Maguire used to be a typical sports agent: willing to do just about anything he could to get the biggest possible contracts for his clients, plus a nice commission for himself. Then, one day, he suddenly has second thoughts about what he’s really doing. When he voices these doubts, he ends up losing his job and all of his clients, save Rod Tidwell, an egomaniacal football player.',
     ARRAY['comedy','drama','sports','romance']),

     ('The Grand Budapest Hotel', 'Wes Anderson', 2014,
     'https://www.imdb.com/title/tt2278388/?ref_=nv_sr_srsg_0_tt_7_nm_1_in_0_q_grand%2520buda',
     'https://letterboxd.com/film/the-grand-budapest-hotel/',
     '/movie_art/grandhotel.jpg',
     'A murder case of Madam D. with enormous wealth and the most outrageous events surrounding her sudden death!',
     'The Grand Budapest Hotel tells of a legendary concierge at a famous European hotel between the wars and his friendship with a young employee who becomes his trusted protégé. The story involves the theft and recovery of a priceless Renaissance painting, the battle for an enormous family fortune and the slow and then sudden upheavals that transformed Europe during the first half of the 20th century.',
     ARRAY['comedy','drama','period drama']),

     ('Tombstone', 'George P. Cosmatos', 1993,
     'https://www.imdb.com/title/tt0108358/?ref_=nv_sr_srsg_0_tt_7_nm_1_in_0_q_tombstone',
     'https://letterboxd.com/film/tombstone/',
     '/movie_art/tombstone.jpg',
     'Every town has a story. Tombstone has a legend.',
     'Legendary marshal Wyatt Earp, now a weary gunfighter, joins his brothers Morgan and Virgil to pursue their collective fortune in the thriving mining town of Tombstone. But Earp is forced to don a badge again and get help from his notorious pal Doc Holliday when a gang of renegade brigands and rustlers begins terrorizing the town.',
     ARRAY['western','action','drama','period drama']),

     ('The Holdovers', 'Alexander Payne', 2023,
     'https://www.imdb.com/title/tt14849194/?ref_=nv_sr_srsg_1_tt_4_nm_4_in_0_q_holdover',
     'https://letterboxd.com/film/the-holdovers/',
     '/movie_art/holdovers.jpg',
     'Discomfort and joy.',
     'A curmudgeonly instructor at a New England prep school is forced to remain on campus during Christmas break to babysit the handful of students with nowhere to go. Eventually, he forms an unlikely bond with one of them — a damaged, brainy troublemaker — and with the school’s head cook, who has just lost a son in Vietnam.',
     ARRAY['comedy','drama','period drama']),

     ('Rounders', 'John Dahl', 1998,
     'https://www.imdb.com/title/tt0128442/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_rounders',
     'https://letterboxd.com/film/rounders/',
     '/movie_art/rounders.jpg',
     'Trust everyone… But always cut the cards.',
     'Poker addict Mike McDermott knows the game inside out, but loses his money one night in a game to Russian-American gangster Teddy KGB. Promising his partner Jo he’ll give up, he meets up with best friend Lester ‘Worm’ Murphy, just out of prison and owing lots of money to the wrong kind of people. McDermott becomes his co-guarantor and now there’s only one way to raise the money, the pair have to get back into the game.',
     ARRAY['drama','crime']),

     ('Pleasantville', 'Gary Ross', 1998,
     'https://www.imdb.com/title/tt0120789/?ref_=nv_sr_srsg_0_tt_6_nm_2_in_0_q_pleasantville',
     'https://letterboxd.com/film/pleasantville/',
     '/movie_art/ville.jpg',
     'Nothing is as simple as black and white.',
     'Geeky teenager David and his popular twin sister, Jennifer, get sucked into the black-and-white world of a 1950s TV sitcom called “Pleasantville,” and find a world where everything is peachy keen all the time. But when Jennifer’s modern attitude disrupts Pleasantville’s peaceful but boring routine, she literally brings color into its life.',
     ARRAY['comedy','drama','fantasy','black and white']),

     ('Glengarry Glen Ross', 'James Foley', 1992,
     'https://www.imdb.com/title/tt0104348/?ref_=nv_sr_srsg_0_tt_6_nm_2_in_0_q_glengarr',
     'https://letterboxd.com/film/glengarry-glen-ross/',
     '/movie_art/glen.jpg',
     'A story for everyone who works for a living.',
     'Times are tough at Premiere Properties. Shelley “the machine” Levene and Dave Moss are veteran salesmen, but only Ricky Roma is on a hot streak. The new Glengarry sales leads could turn everything around, but the front office is holding them back until these “losers” prove themselves. Then someone decides to take matters into his own hands, stealing the Glengarry leads and leaving everyone wondering who did it.',
     ARRAY['drama','mystery','crime','dark comedy']),

     ('Swingers', 'Doug Liman', 1996,
     'https://www.imdb.com/title/tt0117802/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_swingers',
     'https://letterboxd.com/film/swingers/',
     '/movie_art/swing.jpg',
     'Cocktails first. Questions later.',
     'After 6 years together, Mike’s girlfriend leaves him, so he travels to LA to be a star. Six months on, he’s still not doing very well— so a few of his friends try to reconnect him to the social scene and hopefully help him forget his failed relationship.',
     ARRAY['drama','comedy','dark comedy']),

     ('Thank You for Smoking', 'Jason Reitman', 2005,
     'https://www.imdb.com/title/tt0427944/?ref_=fn_t_1',
     'https://letterboxd.com/film/thank-you-for-smoking/',
     '/movie_art/smoking.jpg',
     'Nick Naylor doesn’t hide the truth…he filters it.',
     'Nick Naylor is a charismatic spin-doctor for Big Tobacco who’ll fight to protect America’s right to smoke – even if it kills him – while still remaining a role model for his 12-year old son. When he incurs the wrath of a senator bent on snuffing out cigarettes, Nick’s powers of “filtering the truth” will be put to the test.',
     ARRAY['comedy','drama','dark comedy']),

     ('Rain Man', 'Barry Levinson', 1988,
     'https://www.imdb.com/title/tt0095953/?ref_=fn_t_1',
     'https://letterboxd.com/film/rain-man/',
     '/movie_art/rainman.jpg',
     'A journey through understanding and fellowship.',
     'When car dealer Charlie Babbitt learns that his estranged father has died, he returns home to Cincinnati, where he discovers that he has a savant older brother named Raymond and that his father’s $3 million fortune is being left to the mental institution in which Raymond lives. Motivated by his father’s money, Charlie checks Raymond out of the facility in order to return with him to Los Angeles. The brothers’ cross-country trip ends up changing both their lives.',
     ARRAY['drama','road trip','dark comedy']),

     ('All the President’s Men', 'Alan J. Pakula', 1976,
     'https://www.imdb.com/title/tt0074119/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_all%2520the%2520presid',
     'https://letterboxd.com/film/all-the-presidents-men/',
     '/movie_art/allmen.jpg',
     'The most devastating detective story of this century.',
     'During the 1972 elections, two reporters’ investigation sheds light on the controversial Watergate scandal that compels President Nixon to resign from his post.',
     ARRAY['mystery','thriller','drama','history','political drama']),

     ('Tremors', 'Ron Underwood', 1990,
     'https://www.imdb.com/title/tt0100814/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_tremors',
     'https://letterboxd.com/film/tremors/',
     '/movie_art/tremors.jpg',
     'They say there’s nothing new under the sun. But under the ground…',
     'Val McKee and Earl Bassett are in a fight for their lives when they discover that their desolate town has been infested with gigantic, man-eating creatures that live below the ground.',
     ARRAY['horror','dark comedy','comedy','adventure','action','sci-fi']),

     ('Platoon', 'Oliver Stone', 1986,
     'https://www.imdb.com/title/tt0091763/?ref_=fn_t_1',
     'https://letterboxd.com/film/platoon/',
     '/movie_art/platoon.jpg',
     'The first casualty of war is innocence.',
     'As a young and naive recruit in Vietnam, Chris Taylor faces a moral crisis when confronted with the horrors of war and the duality of man.',
     ARRAY['war','action','drama']),

     ('The Year of Living Dangerously', 'Peter Weir', 1982,
     'https://www.imdb.com/title/tt0086617/?ref_=nv_sr_srsg_0_tt_4_nm_4_in_0_q_the%2520year%2520of%2520living',
     'https://letterboxd.com/film/the-year-of-living-dangerously/',
     '/movie_art/yeardanger.jpg',
     'A love caught in the fire of revolution.',
     'A young Australian reporter tries to navigate the political turmoil of Indonesia during the rule of President Sukarno with the help of a diminutive photographer.',
     ARRAY['war','romance','drama','period drama','history']),

     ('La La Land', 'Damien Chazelle', 2016,
     'https://www.imdb.com/title/tt3783958/?ref_=nv_sr_srsg_5_tt_2_nm_6_in_0_q_la%2520la%2520',
     'https://letterboxd.com/film/la-la-land/',
     '/movie_art/lala.jpg',
     'Here’s to the fools who dream.',
     'Mia, an aspiring actress, serves lattes to movie stars in between auditions and Sebastian, a jazz musician, scrapes by playing cocktail party gigs in dingy bars, but as success mounts they are faced with decisions that begin to fray the fragile fabric of their love affair, and the dreams they worked so hard to maintain in each other threaten to rip them apart.',
     ARRAY['drama','romance','comedy','music']),

     ('Everything Everywhere All at Once', 'Daniels', 2022,
     'https://www.imdb.com/title/tt6710474/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_everything%2520everwhere',
     'https://letterboxd.com/film/everything-everywhere-all-at-once/',
     '/movie_art/everything.jpg',
     'The universe is so much bigger than you realize.',
     'An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what’s important to her by connecting with the lives she could have led in other universes.',
     ARRAY['sci-fi','surreal','comedy','drama','action','epic','adventure','dark comedy']),

     ('Sleuth', 'Joseph L. Mankiewicz', 1972,
     'https://www.imdb.com/title/tt0069281/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_sleuth',
     'https://letterboxd.com/film/sleuth/',
     '/movie_art/sleuth.jpg',
     'Think of the perfect crime… Then go one step further.',
     'A man who loves games and theater invites his wife’s lover to meet him, setting up a battle of wits with potentially deadly results.',
     ARRAY['crime','mystery','thriller']),

     ('Remember the Titans', 'Boaz Yakin', 2000,
     'https://www.imdb.com/title/tt0210945/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_remember%2520the%2520titans',
     'https://letterboxd.com/film/remember-the-titans/',
     '/movie_art/titans.jpg',
     'History is written by the winners.',
     'After leading his football team to 15 winning seasons, coach Bill Yoast is demoted and replaced by Herman Boone – tough, opinionated and as different from the beloved Yoast as he could be. The two men learn to overcome their differences and turn a group of hostile young men into champions.',
     ARRAY['sports','drama','period drama','comedy']),

     ('The Suicide Squad', 'James Gunn', 2021,
     'https://www.imdb.com/title/tt6334354/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_the%2520suicide%2520',
     'https://letterboxd.com/film/the-suicide-squad/',
     '/movie_art/squad.jpg',
     'They’re dying to save the world.',
     'Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.',
     ARRAY['action','adventure','comedy','superhero']),

     ('The Long Goodbye', 'Robert Altman', 1973,
     'https://www.imdb.com/title/tt0070334/?ref_=fn_t_1',
     'https://letterboxd.com/film/the-long-goodbye/',
     '/movie_art/goodbye.jpg',
     'Nothing says goodbye like a bullet…',
     'In 1970s Hollywood, Detective Philip Marlowe tries to help a friend who is accused of murdering his wife.',
     ARRAY['crime','mystery','film noir','drama','thriller']),

     ('Young Frankenstein', 'Mel Brooks', 1974,
     'https://www.imdb.com/title/tt0072431/?ref_=nv_sr_srsg_0_tt_6_nm_2_in_0_q_young%2520fra',
     'https://letterboxd.com/film/young-frankenstein/',
     '/movie_art/young.jpg',
     'The scariest comedy of all time!',
     'A young neurosurgeon inherits the castle of his grandfather, the famous Dr. Victor von Frankenstein. In the castle he finds a funny hunchback, a pretty lab assistant and the elderly housekeeper. Young Frankenstein believes that the work of his grandfather was delusional, but when he discovers the book where the mad doctor described his reanimation experiment, he suddenly changes his mind.',
     ARRAY['comedy','farce','parody','slapstick','dark comedy']),

     ('Airplane!', 'Jerry Zucker', 1980,
     'https://www.imdb.com/title/tt0080339/?ref_=nv_sr_srsg_0_tt_7_nm_1_in_0_q_airplane',
     'https://letterboxd.com/film/airplane/',
     '/movie_art/airplane.jpg',
     'What’s slower than a speeding bullet, and able to hit tall buildings at a single bound?',
     'An ex-fighter pilot forced to take over the controls of an airliner when the flight crew succumbs to food poisoning.',
     ARRAY['comedy','slapstick','farce','parody','dark comedy']),

     ('Pineapple Express', 'David Gordon Green', 2008,
     'https://www.imdb.com/title/tt0910936/?ref_=nv_sr_srsg_0_tt_6_nm_2_in_0_q_pineapl',
     'https://letterboxd.com/film/pineapple-express/',
     '/movie_art/pine.jpg',
     'Put this in your pipe and smoke it.',
     'A stoner and his dealer are forced to go on the run from the police after the pothead witnesses a cop commit a murder.',
     ARRAY['comedy','stoner comedy','action','crime']),

     ('Happy Gilmore', 'Dennis Dugan', 1996,
     'https://www.imdb.com/title/tt0116483/?ref_=nv_sr_srsg_3_tt_8_nm_0_in_0_q_happy%2520gilmore',
     'https://letterboxd.com/film/happy-gilmore/',
     '/movie_art/happy.jpg',
     'He doesn’t play golf… he destroys it.',
     'Failed hockey player-turned-golf whiz Happy Gilmore — whose unconventional approach and antics on the green courts the ire of rival Shooter McGavin — is determined to win a PGA tournament so he can save his granny’s house with the prize money. Meanwhile, an attractive tour publicist tries to soften Happy’s image.',
     ARRAY['comedy','sports','slapstick']),

     ('Office Space', 'Mike Judge', 1999,
     'https://www.imdb.com/title/tt0151804/?ref_=fn_t_1',
     'https://letterboxd.com/film/office-space/',
     '/movie_art/office.jpg',
     'Work sucks.',
     'A depressed white-collar worker tries hypnotherapy, only to find himself in a perpetual state of devil-may-care bliss that prompts him to start living by his own rules, and hatch a hapless attempt to embezzle money from his soul-killing employers.',
     ARRAY['comedy','dark comedy']),

     ('Tommy Boy', 'Peter Segal', 1995,
     'https://www.imdb.com/title/tt0114694/?ref_=fn_t_1',
     'https://letterboxd.com/film/tommy-boy/',
     '/movie_art/tommy.jpg',
     'If at first you don’t succeed, lower your standards.',
     'To save the family business, two ne’er-do-well traveling salesmen hit the road with disastrously funny consequences.',
     ARRAY['comedy','road trip','slapstick','adventure']),

     ('Best in Show', 'Christopher Guest', 2000,
     'https://www.imdb.com/title/tt0218839/?ref_=fn_t_1',
     'https://letterboxd.com/film/best-in-show/',
     '/movie_art/bestshow.jpg',
     'Some pets deserve a little more respect than others.',
     'The tension is palpable, the excitement is mounting and the heady scent of competition is in the air as hundreds of eager contestants from across America prepare to take part in what is undoubtedly one of the greatest events of their lives – the Mayflower Dog Show. The canine contestants and their owners are as wondrously diverse as the great country that has bred them.',
     ARRAY['comedy','mockumentary']),

     ('A Mighty Wind', 'Christopher Guest', 2003,
     'https://www.imdb.com/title/tt0310281/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_a%2520mighty%2520wind',
     'https://letterboxd.com/film/a-mighty-wind/',
     '/movie_art/wind.jpg',
     'Back together for the first time, again.',
     'Three eclectic, never-quite-famous folk bands come together for the first time in decades following the death of their manager to put on an reunion concert in his honor, at the request of his son.',
     ARRAY['comedy','mockumentary','music']),

     ('Wayne’s World', 'Penelope Spheeris', 1992,
     'https://www.imdb.com/title/tt0105793/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_waynes%2520world',
     'https://letterboxd.com/film/waynes-world/',
     '/movie_art/waynes.jpg',
     'You’ll laugh. You’ll cry. You’ll hurl.',
     'The adventures of two amiably aimless metal-head friends, Wayne and Garth. From Wayne’s basement, the pair broadcast a talk-show called “Wayne’s World” on local public access television. The show comes to the attention of a sleazy network executive who wants to produce a big-budget version of “Wayne’s World”—and he also wants Wayne’s girlfriend, a rock singer named Cassandra. Wayne and Garth have to battle the executive not only to save their show, but also Cassandra',
     ARRAY['comedy','music','slapstick']),

     ('Major League', 'David S. Ward', 1989,
     'https://www.imdb.com/title/tt0097815/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_major%2520league',
     'https://letterboxd.com/film/major-league/',
     '/movie_art/majorleague.jpg',
     'A comedy with bats and balls.',
     'When Rachel Phelps inherits the Cleveland Indians from her deceased husband, she’s determined to move the team to a warmer climate—but only a losing season will make that possible, which should be easy given the misfits she’s hired. Rachel is sure her dream will come true, but she underestimates their will to succeed.',
     ARRAY['comedy','sports']),

     ('My Cousin Vinny', 'Jonathan Lynn', 1992,
     'https://www.imdb.com/title/tt0104952/?ref_=nv_sr_srsg_0_tt_3_nm_0_in_0_q_my%2520cousin%2520vinny',
     'https://letterboxd.com/film/my-cousin-vinny/',
     '/movie_art/vinny.jpg',
     'There have been many courtroom dramas that have glorified the Great American Legal System. This is not one of them.',
     'Two carefree pals from Brooklyn traveling through rural Alabama on their way back to college are mistakenly arrested, and charged with murder. Fortunately, one of them has a cousin who’s a lawyer - Vincent Gambini, a former auto mechanic from Brooklyn who just passed his bar exam after his sixth try. When he arrives with his leather-clad girlfriend, to try his first case, it’s a real shock - for him and the Deep South!',
     ARRAY['comedy','crime','drama']),

     ('What We Do in the Shadows', 'Jemaine Clement', 2014,
     'https://www.imdb.com/title/tt3416742/?ref_=nv_sr_srsg_3_tt_8_nm_0_in_0_q_what%2520we%2520do%2520in%2520the%2520',
     'https://letterboxd.com/film/what-we-do-in-the-shadows/',
     '/movie_art/shadows.jpg',
     'Some interviews with some vampires.',
     'Vampire housemates try to cope with the complexities of modern life and show a newly turned hipster some of the perks of being undead.',
     ARRAY['comedy','dark comedy','mockumentary','horror']),

     ('The Princess Bride', 'Rob Reiner', 1987,
     'https://www.imdb.com/title/tt0093779/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_princess%2520bride',
     'https://letterboxd.com/film/the-princess-bride/',
     '/movie_art/bride.jpg',
     'It’s as real as the feelings you feel.',
     'In this enchantingly cracked fairy tale, the beautiful Princess Buttercup and the dashing Westley must overcome staggering odds to find happiness amid six-fingered swordsmen, murderous princes, Sicilians and rodents of unusual size. But even death can’t stop these true lovebirds from triumphing.',
     ARRAY['fantasy','romance','comedy','adventure']),

     ('This is Spinal Tap', 'Rob Reiner', 1984,
     'https://www.imdb.com/title/tt0088258/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_this%2520is%2520spin',
     'https://letterboxd.com/film/this-is-spinal-tap/',
     '/movie_art/spinal.jpg',
     'Prepare to crank those amps up to eleven.',
     '“This Is Spinal Tap” shines a light on the self-contained universe of a metal band struggling to get back on the charts, including everything from its complicated history of ups and downs, gold albums, name changes and undersold concert dates, along with the full host of requisite groupies, promoters, hangers-on and historians, sessions, release events and those special behind-the-scenes moments that keep it all real.',
     ARRAY['comedy','mockumentary','music','parody']),

     ('In the Loop', 'Armando Iannucci', 2009,
     'https://www.imdb.com/title/tt1226774/?ref_=nv_sr_srsg_2_tt_8_nm_0_in_0_q_in%2520the%2520loop',
     'https://letterboxd.com/film/in-the-loop/',
     '/movie_art/loop.jpg',
     'The fate of the world is on the line.',
     'The US President and the UK Prime Minister are planning on launching a war in the Middle East, but—behind the scenes—government officials and advisers are either promoting the war or are trying to prevent it.',
     ARRAY['comedy','political comedy']),

     ('Dazed and Confused', 'Richard Linklater', 1993,
     'https://www.imdb.com/title/tt0106677/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_dazed%2520',
     'https://letterboxd.com/film/dazed-and-confused/',
     '/movie_art/dazed.jpg',
     'It was the last day of school in 1976. A time they’d never forget. (If only they could remember)',
     'The adventures of a group of Texas teens on their last day of school in 1976, centering on student Randall Floyd, who moves easily among stoners, jocks and geeks. Floyd is a star athlete, but he also likes smoking weed, which presents a conundrum when his football coach demands he sign a “no drugs” pledge.',
     ARRAY['comedy','stoner comedy']),

     ('School of Rock', 'Richard Linklater', 2003,
     'https://www.imdb.com/title/tt0332379/?ref_=nv_sr_srsg_1_tt_6_nm_1_in_0_q_school%2520of%2520rock',
     'https://letterboxd.com/film/school-of-rock/',
     '/movie_art/rock.jpg',
     'We don’t need no education.',
     'Fired from his band and hard up for cash, guitarist and vocalist Dewey Finn finagles his way into a job as a fifth-grade substitute teacher at a private school, where he secretly begins teaching his students the finer points of rock ’n’ roll. The school’s hard-nosed principal is rightly suspicious of Finn’s activities. But Finn’s roommate remains in the dark about what he’s doing.',
     ARRAY['comedy','music']),

     ('Galaxy Quest', 'Dean Parisot', 1999,
     'https://www.imdb.com/title/tt0177789/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_galaxy%2520quest',
     'https://letterboxd.com/film/galaxy-quest/',
     '/movie_art/galaxy.jpg',
     'A comedy of galactic proportions.',
     'For four years, the courageous crew of the NSEA Protector — Commander Peter Quincy Taggart, Lieutenant Tawny Madison, and Doctor Lazarus — set off on a thrilling and often dangerous mission in space … until their series was cancelled! Now, twenty years later, aliens under attack have mistaken the Galaxy Quest television transmissions for “historical documents” and beam up the crew of has-been actors to save the universe. With no script, no director, and no clue, the actors must turn in the performances of their lives.',
     ARRAY['comedy','sci-fi','parody','adventure']),

     ('City Slickers', 'Ron Underwood', 1991,
     'https://www.imdb.com/title/tt0101587/?ref_=nv_sr_srsg_0_tt_7_nm_1_in_0_q_city%2520slickers',
     'https://letterboxd.com/film/city-slickers/',
     '/movie_art/slickers.jpg',
     'Yesterday they were businessmen. Today they’re cowboys. Tomorrow they’ll be walking funny.',
     'Three New York businessmen decide to take a “Wild West” vacation that turns out not to be the relaxing vacation they had envisioned.',
     ARRAY['comdey','western']),

     ('Kung Fu Hustle', 'Stephen Chow', 2004,
     'https://www.imdb.com/title/tt0373074/?ref_=nv_sr_srsg_0_tt_7_nm_1_in_0_q_kung%2520fu%2520hus',
     'https://letterboxd.com/film/kung-fu-hustle/',
     '/movie_art/hustle.jpg',
     'So many gangsters… so little time.',
     'It’s the 1940s, and the notorious Axe Gang terrorizes Shanghai. Small-time criminals Sing and Bone hope to join, but they only manage to make lots of very dangerous enemies. Fortunately for them, kung fu masters and hidden strength can be found in unlikely places. Now they just have to take on the entire Axe Gang.',
     ARRAY['comedy','action','dark comedy','kung fu','chinese']),

     ('Burn After Reading', 'Coen Brothers', 2008,
     'https://www.imdb.com/title/tt0887883/?ref_=fn_t_1',
     'https://letterboxd.com/film/burn-after-reading/',
     '/movie_art/reading.jpg',
     'Intelligence is relative.',
     'When a disc containing memoirs of a former CIA analyst falls into the hands of gym employees, Linda and Chad, they see a chance to make enough money for Linda to have life-changing cosmetic surgery. Predictably, events whirl out of control for the duo, and those in their orbit.',
     ARRAY['dark comedy','comdey','crime','drama','thriller']),

     ('So I Married an Axe Murderer', 'Thomas Schlamme', 1993,
     'https://www.imdb.com/title/tt0108174/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_so%2520i%2520mar',
     'https://letterboxd.com/film/so-i-married-an-axe-murderer/',
     '/movie_art/axe.jpg',
     'The honeymoon was killer.',
     'Just after a bad breakup, Charlie MacKenzie falls for lovely butcher Harriet Michaels and introduces her to his parents. But, as voracious consumers of sensational tabloids, his parents soon come to suspect that Harriet is actually a notorious serial killer – “Mrs. X” – wanted in connection with a string of bizarre honeymoon killings. Thinking his parents foolish, Charlie proposes to Harriet. But while on his honeymoon with her, he begins to fear they were right.',
     ARRAY['dark comedy','romance','comedy']),

     ('Three Kings', 'David O. Russell', 1999,
     'https://www.imdb.com/title/tt0120188/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_Three%2520Kings',
     'https://letterboxd.com/film/three-kings/',
     '/movie_art/threekings.jpg',
     'It’s good to be king.',
     'A group of American soldiers stationed in Iraq at the end of the Gulf War find a map they believe will take them to a huge cache of stolen Kuwaiti gold hidden near their base, and they embark on a secret mission that’s destined to change everything.',
     ARRAY['war','action','dark comedy','adventure']),

     ('World’s Greatest Dad', 'Bobcat Goldthwait', 2009,
     'https://www.imdb.com/title/tt1262981/?ref_=nv_sr_srsg_0_tt_7_nm_1_in_0_q_world%27s%2520greatest%2520dad',
     'https://letterboxd.com/film/worlds-greatest-dad/',
     '/movie_art/dad.jpg',
     'Lance Clayton is about to get everything he deserves.',
     'In the wake of a freak accident, Lance suffers the worst tragedy and the greatest opportunity of his life. He is suddenly faced with the possibility of fame, fortune and popularity, if he can only live with the knowledge of how he got there.',
     ARRAY['dark comedy','comedy','drama']),

     ('Speed', 'Jan de Bont', 1994,
     'https://www.imdb.com/title/tt0111257/?ref_=nv_sr_srsg_0_tt_6_nm_2_in_0_q_speed',
     'https://letterboxd.com/film/speed/',
     '/movie_art/speed.jpg',
     'Get ready for rush hour.',
     'Jack Traven, an LAPD cop on SWAT detail, and veteran SWAT officer Harry Temple thwart an extortionist-bomber’s scheme for a $3 million ransom. As they corner the bomber, he flees and detonates a bomb vest, seemingly killing himself. Weeks later, Jack witnesses a mass transit city bus explode and nearby a pay phone rings. On the phone is that same bomber looking for vengeance and the money he’s owed. He gives a personal challenge to Jack: a bomb is rigged on another city bus - if it slows down below 50 mph, it will explode - bad enough any day, but a nightmare in LA traffic. And that’s just the beginning…',
     ARRAY['action','thriller','adventure','road trip']),

     ('Conclave', 'Edward Berger', 2024,
     'https://www.imdb.com/title/tt20215234/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_conclave',
     'https://letterboxd.com/film/conclave/',
     '/movie_art/conclave.jpg',
     'What happens behind these walls will change everything.',
     'After the unexpected death of the Pope, Cardinal Lawrence is tasked with managing the covert and ancient ritual of electing a new one. Sequestered in the Vatican with the Catholic Church’s most powerful leaders until the process is complete, Lawrence finds himself at the center of a conspiracy that could lead to its downfall.',
     ARRAY['drama','thriller']),

     ('Dawn of the Dead', 'Zach Snyder', 2004,
     'https://www.imdb.com/title/tt0363547/?ref_=fn_t_1',
     'https://letterboxd.com/film/dawn-of-the-dead-2004/',
     '/movie_art/dawndead.jpg',
     'When there’s no more room in Hell, the dead will walk the Earth.',
     'A group of survivors take refuge in a shopping mall after the world is taken over by aggressive, flesh-eating zombies.',
     ARRAY['horror','action','zombies','dark comedy']),

     ('Sling Blade', 'Billy Bob Thorton', 1996,
     'https://www.imdb.com/title/tt0117666/?ref_=nv_sr_srsg_0_tt_4_nm_4_in_0_q_slingblad',
     'https://letterboxd.com/film/sling-blade/',
     '/movie_art/slingblade.jpg',
     'A simple man. A difficult choice.',
     'Karl Childers, a mentally disabled man, has been in the custody of the state mental hospital since the age of 12 for killing his mother and her lover. Although thoroughly institutionalized, he is deemed fit to be released into the outside world.',
     ARRAY['drama','tragedy'])



ON CONFLICT ON CONSTRAINT uq_movie_title_year DO NOTHING;
